### ISSUE TITLE
List on keycloak.org extensions page

### ISSUE THREAD

**Issue by stianst** [cloudtrust/keycloak-wsfed#29]
Would be great to see this extension listed on the keycloak.org extensions page. To do that simply send a PR to https://github.com/keycloak/keycloak-web/tree/master/src/main/resources/extensions. You can find a template for the required json file here https://github.com/keycloak/keycloak-web/blob/master/src/main/resources/extension-template.json.

**Comment by AlistairDoswald** [comment]
Thanks for the suggestion! I did the pull request.
