### ISSUE TITLE
Maven build on master does not work

### ISSUE THREAD

**Issue by groissi** [cloudtrust/keycloak-wsfed#39]
Sorry for this probably dumb question, but I'm not able to build the module using Maven. I tried to use:
`mvn clean install -DskipTests -U`

The problem is that Maven can not find the parent artifact of the pom:
```
    <parent>
        <groupId>org.keycloak.testsuite</groupId>
        <artifactId>integration-arquillian-tests</artifactId>
        <version>6.0.1</version>
    </parent>
```

I have configured the `jboss-ga-repository`, `jboss-ga-plugin-repository`, `jboss-earlyaccess-repository`, and `jboss-earlyaccess-plugin-repository` Maven repositories in my settings.xml. None of these repos contains that pom. I also searched the web for any other repo, but didn't find any repo containing that parent artifact.

How can I build your module? Maybe adding the description to the README would be good for others, too.

**Comment by brat000012001** [comment]
You may want to check the discussion in #35

**Comment by groissi** [comment]
Okay, so you have to build `KeyCloak` itself locally using `mvn clean install -DskipTests` in order for the special jars to be available in the local Maven repository.

Not ideal solution, but works for me now.
