### ISSUE TITLE
Migrate to Keycloak 8.0.1

### ISSUE THREAD

**Issue by brat000012001** [cloudtrust/keycloak-wsfed#43]
Keycloak release version 8.0.1 has been released a few days ago. To keep the release schedule of keycloak-wsfed not too far behind the keycloak releases, it would be a good idea to migrate the module to KC 8.0.1. See #40

**Comment by lagess** [comment]
I agree this module needs to be upgraded. As we are currently pretty busy with many other topic, this is not "high priority" in our task list. PRs are always welcome :-)

**Comment by vanrar68** [comment]
@lagess can you build a release with current state of master please ? I backported all keycloak 8.0.1 changes to it. Thanks

**Comment by fperot74** [comment]
Sorry, we don't have a CI which publishes our components to a public repository. We only have them in a private one.
Note that we are planning to migrate to Keycloak 10.x soon (and the 11.x when it will be available)

**Comment by lelvisl** [comment]
any updates?

**Comment by fperot74** [comment]
Migration to Keycloak 8.0.1 has already been implemented, thanks to a contribution from @vanrar68
This issue should be closed for 2 months
