### ISSUE TITLE
Client installation page is broken

### ISSUE THREAD

**Issue by AlistairDoswald** [cloudtrust/keycloak-wsfed#5]
Moving to the Client>Installation page for a WS-Fed Client will result in a clearly broken page with the template exposed instead of having a normal page from which the installation details may be obtained.

A workaround is available, as the necessary information can be obtain with the `https://<address:port>/auth/realms/<Realm name>/protocol/<protocol type>/descriptor` URL. 

This should however be corrected so that the information can be obtained as for clients of the other protocols.

**Comment by yelhouti** [comment]
The problem wasn't it the javascript but in the java code it is normally fixed now with.
