### ISSUE TITLE
support for ws-trust

### ISSUE THREAD

**Issue by sumantfordev** [cloudtrust/keycloak-wsfed#58]
i don't believe this extension supports WS-Trust as well, does it?
I am seriously planning to use this extension for what it provides, Any idea what would be the effort to implement it in this extension itself?

**Comment by fperot74** [comment]
I don't believe so but, as WS-Fed is an extension of WS-Trust, may be the effort wouldn't be a huge one. But I don't have WS-Trust knowledge to answer more precisely
