### ISSUE TITLE
Migrate to keycloak v15 (at least v13)

### ISSUE THREAD

**Issue by turlarion** [cloudtrust/keycloak-wsfed#59]
Are you planning to migrate to current versions of keycloak?
There is already keycloak v 15.0.1, but the current code doesn't suite

**Comment by fperot74** [comment]
Hello,
keycloak-wsfed is currently not used in our product so we are not maintaining it any more.
I quickly tried to upgrade it (14.0) but build is failing. I created a pull request in the state I was stuck in this project. You are free to get my branch if you want to finish migrating this module but we have no planned time to do it.
