### ISSUE TITLE
Keycloak 22+ Support Request

### ISSUE THREAD

**Issue by ghost** [cloudtrust/keycloak-wsfed#61]
Hi,

I just installing Keycloak 22.0.3 on Ubuntu 22.04 with OpenJDK 19 and Maven 3.9, and try to configure it with this extension. It seems this extension can't be build anymore. May I know, do you have any intention to upgrade this extension to support newer version of Keycloak?

Thank you.

**Comment by fperot74** [comment]
This version could be built with the correct version of the cloudtrust-parent dependency (it might be possible to find the correct one by watching the dates of commits)... but it would not be compatible with Keycloak 22.
Perhaps in the future? But currently, this module is not maintained anymore.
